# Generated by Django 4.2.3 on 2023-07-26 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], max_length=2)),
                ('hiring_cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[], max_length=2)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tresury', models.PositiveIntegerField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbm_app.race')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('max_number', models.PositiveIntegerField()),
                ('ma', models.PositiveIntegerField()),
                ('st', models.PositiveIntegerField()),
                ('ag', models.PositiveIntegerField()),
                ('av', models.PositiveIntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('primary_skills', models.ManyToManyField(related_name='positions_primary', to='bbm_app.skill')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='bbm_app.race')),
                ('secondary_skills', models.ManyToManyField(related_name='positions_secondary', to='bbm_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.PositiveIntegerField(choices=[(1, 'Rookie'), (2, 'Experienced'), (3, 'Veteran'), (4, 'Star'), (5, 'Super Star'), (6, 'Legend')])),
                ('spp', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('ma', models.PositiveIntegerField()),
                ('st', models.PositiveIntegerField()),
                ('ag', models.PositiveIntegerField()),
                ('av', models.PositiveIntegerField()),
                ('pa', models.PositiveIntegerField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbm_app.position')),
                ('skills', models.ManyToManyField(to='bbm_app.skill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbm_app.team')),
            ],
        ),
    ]
