# Generated by Django 4.2.3 on 2023-07-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='bbm_app.coach'),
        ),
    ]
