# Generated by Django 4.2.3 on 2023-07-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0003_racepositionlimit_delete_event_delete_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='traits',
            field=models.ManyToManyField(to='bbm_app.trait'),
        ),
    ]
