# Generated by Django 4.2.3 on 2023-07-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0004_trait_player_traits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('AMA', 'Amazon'), ('CDW', 'Chaos Dwarf'), ('CHA', 'Chaos Chosen'), ('DWF', 'Dwarf'), ('ELV', 'Elven Union'), ('GOB', 'Goblin'), ('HAF', 'Halfling'), ('PRO', 'Pro Elf'), ('HUM', 'Human'), ('LIZ', 'Lizardmen'), ('NEC', 'Necromantic Horror'), ('NOR', 'Norse'), ('OGR', 'Ogre'), ('ORC', 'Orc'), ('SKA', 'Skaven'), ('UND', 'Undead'), ('WOD', 'Wood Elf'), ('BLO', 'Black Orc'), ('IMP', 'Imperial Nobility'), ('SNO', 'Snotling'), ('OWA', 'Old World Alliance')], default='AMA', max_length=3, unique=True),
        ),
    ]
