# Generated by Django 4.2.3 on 2023-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0005_team_draws_team_losses_team_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='passing',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
