# Generated by Django 4.2.3 on 2023-07-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0006_position_traits_alter_race_race_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='Agility',
            new_name='agility',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Armor',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Movement',
            new_name='movement',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Passing',
            new_name='passing',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='Strength',
            new_name='strength',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Agility',
            new_name='agility',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Armor',
            new_name='armor',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Movement',
            new_name='movement',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Passing',
            new_name='passing',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='Strength',
            new_name='strength',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('skills', models.ManyToManyField(related_name='categories', to='bbm_app.skill')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='primary_skill_categories',
            field=models.ManyToManyField(related_name='primary_positions', to='bbm_app.skillcategory'),
        ),
        migrations.AddField(
            model_name='position',
            name='secondary_skill_categories',
            field=models.ManyToManyField(blank=True, related_name='secondary_positions', to='bbm_app.skillcategory'),
        ),
    ]
