# Generated by Django 4.2.3 on 2023-07-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbm_app', '0007_rename_agility_player_agility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='former_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='former_players', to='bbm_app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='graveyard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dead_players', to='bbm_app.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='is_journeyman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('dead', 'Dead')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='teams', to='bbm_app.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_players', to='bbm_app.team'),
        ),
        migrations.AlterField(
            model_name='position',
            name='passing',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(blank=True, choices=[('AMA', 'Amazon'), ('CDW', 'Chaos Dwarf'), ('CHA', 'Chaos Chosen'), ('DWF', 'Dwarf'), ('ELV', 'Elven Union'), ('GOB', 'Goblin'), ('HAF', 'Halfling'), ('HUM', 'Human'), ('LIZ', 'Lizardmen'), ('NEC', 'Necromantic Horror'), ('NOR', 'Norse'), ('OGR', 'Ogre'), ('ORC', 'Orc'), ('SKA', 'Skaven'), ('UND', 'Undead'), ('WOD', 'Wood Elf'), ('BLA', 'Black Orc'), ('IMP', 'Imperial Nobility'), ('SNO', 'Snotling'), ('OWA', 'Old World Alliance'), ('DAR', 'Dark Elf'), ('HIG', 'High Elf'), ('NUR', 'Nurgle'), ('KHO', 'Khorne')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'number')},
        ),
        migrations.CreateModel(
            name='Graveyard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(related_name='dead', to='bbm_app.player')),
            ],
        ),
    ]
